version: "3.3"

services:
  # PostgreSQL container
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  # Adminer running on port 1080
  adminer:
    depends_on:
      - db
    image: adminer:latest
    ports:
      - "1080:8080"
    networks:
      - default

  # PHP stuff.
  php:
    depends_on:
      - db
    build: .
    ports:
      - "80:80"
    user: "1000"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - default
